.gitignore
api/responder.xql
api/tlsapi.xql
modules/app.xql
modules/import.xql
modules/krx-utils.xql
modules/wikidata.xql
resources/scripts/tls-webapp.js

This is not complete, we want also retrieve more information from wikidata.

Register Wikidata IDs (qitems) in the database

---

api/tlsapi.xql
modules/app.xql
modules/db-utility.xqm
modules/dialogs.xql
modules/tlslib.xql
resources/scripts/tls-webapp.js

Per-text editing permissions

---

modules/import.xql
modules/tlslib.xql
modules/xml-edit.xql

It' still quite a hack, but it works:-)

Slightly better display of textcritical notes

---

api/tlsapi.xql
modules/admin/text-editing-permissions.xql
resources/scripts/tls-webapp.js

The code for editing the permissions is now in a separate file.  It needs to be owned by group dba and have the setuid bit set.

Fixed bug with text-editing-permissions.

---

char.html
controller.xql
modules/app.xql
modules/view.xql

Contains also updates to the search code.

Some changes to the templating of char. etc.

---

api.html
api.json
lineview.html
modules/api.xql
modules/facsimile.xql
modules/hobotei.xql
modules/layout.xql
modules/signup.xql
resources/scripts/tls-layout.js

Not all files are yet ready, but because they are referenced, they need to be there.

A bunch of new files

---

modules/tlslib.xql

This partially implements #72 .

Creator transparency for attributions.

---

modules/app.xql
modules/tlslib.xql
resources/css/style.css

This is the code, not the font.

Small seal font with unicode cp.

---

api.json
api/responder.xql
api/tlsapi.xql
modules/app.xql
modules/biblio.xql
modules/config.xqm
modules/dialogs.xql
modules/tlslib.xql
modules/wikidata.xql
modules/xml-edit.xql
resources/scripts/tls-webapp.js

Some of the other changes are not ready, but should not cause problems, hopefully.

Implemented Pastebox &other minor changes.

---

api/tlsapi.xql
modules/app.xql
modules/search.xql
resources/scripts/tls-webapp.js

Pastebox still has a few quirks, but is mainly functional now.  
A bug reported by CH concerning search for 或.或. is also fixed.

Bug fix and pastebox improvements

---

api/tlsapi.xql
char.html
modules/app.xql
modules/dialogs.xql
modules/tlslib.xql
resources/scripts/tls-webapp.js

Add char info to tax-char display +bugfixes.

---

modules/app.xql
modules/biblio.xql
modules/tlslib.xql
resources/scripts/tls-webapp.js

This implements adding and editing MODS records in a highly limited fashion.  It also allows connecting bibliographic records to the witness list of texts, thus providing the basis for critical textual editing.

Bibliography module 

---

api/tlsapi.xql
modules/app.xql
modules/dialogs.xql
modules/import.xql
modules/search.xql
modules/tlslib.xql
resources/scripts/tls-webapp.js

Also a big performance hog in app:tv-data

Fixes for search and app-editing

---

api/tlsapi.xql
modules/admin/import-kaixi.xql
modules/admin/run-cbeta-import.xql
modules/app.xql
modules/biblio.xql
modules/dialogs.xql
modules/text-crit.xql
modules/tlslib.xql
resources/scripts/tls-webapp.js

Bugfixes and improvements for the text critical editing (adding references to notes) and biblio: adding URLs to a bib entry.

Bugfixes, text-critic editing & biblio

---

api/new_translation.xql
api/responder.xql
api/store_new_translation.xql
api/tlsapi.xql
modules/admin/changepw.xql
modules/app.xql
modules/dialogs.xql
modules/import.xql
modules/layout.xql
modules/search.xql
modules/tlslib.xql
modules/tlsutils.xql
resources/scripts/tls-webapp.js

Edit of translation files metadata, 
Starting a rewrite of dialogs, beginning with the new ones. 
Also started a new module tlsutils.xql, the plan is to move some stuff from tlslib there, because that is too big and is causing headaches. 
Added textinfo to the catalog list. 
Added a file for password change, that feature is not yet complete.

A big commit with many things

---

modules/app.xql
modules/dialogs.xql
modules/import.xql
modules/search.xql
modules/tlslib.xql
resources/scripts/tls-webapp.js

Also: generic import for TEI documents: imp:tei-conversion

Search config for classified search.

---

api/tlsapi.xql
modules/dialogs.xql
modules/tlslib.xql
modules/xml-edit.xql
resources/scripts/tls-webapp.js

These updates are not yet on the krx development machine

Recent emergency updates from apollo

---

api/search_att.xql
api/tlsapi.xql
concept.html
interface/settings.xml
modules/app.xql
modules/config.xqm
modules/dialogs.xql
modules/lib/citations.xqm
modules/lib/concept.xqm
modules/lib/permissions.xqm
modules/lib/render-html.xqm
modules/lib/special-interest.xqm
modules/lib/swl-dialog.xqm
modules/lib/syn-func.xqm
modules/lib/taxonomy.xqm
modules/lib/user-settings.xqm
modules/lib/word.xqm
modules/tlslib.xql
resources/scripts/tls-webapp.js

And lots of other changes, especially regarding user settings and external resources.

Big update with concept display rewrite

---

modules/app.xql
modules/config.xqm
modules/lib/concept.xqm
modules/lib/syn-func.xqm
modules/lib/word.xqm
modules/tlslib.xql
modules/tlsutils.xql
repo.xml
resources/scripts/tls-webapp.js

After this update, some changes to tls-data will need to be performed:
- move tei:entry out of the concept files to tls-data/words
- update the tls:att counts on the tei:entry and tei:sense @n 
- disable moving of entries etc from concept to concept, this is still not properly tested

Laying the ground for the big update

---

api/tlsapi.xql
modules/lib/translation.xqm

This creates not licensed translation files in the non-free hierarchy.

Bugfix for new translations.
